name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Download Model
        run: mkdir -p models && curl -L https://huggingface.co/TheBloke/Llama-2-7B-GGUF/resolve/main/llama-2-7b.Q2_K.gguf >models/llama-2-7b.Q2_K.gguf
      - name: Build
        run: mkdir -p build && cd build && cmake .. && make -j$(nproc)
      - name: Test
        run: ./build/backend/backend_test
